import { api } from "./client.js";

function qs(params = {}) {
  const entries = Object.entries(params).filter(([, v]) => v !== undefined && v !== "" && v !== null);
  if (!entries.length) return "";
  return "?" + new URLSearchParams(entries).toString();
}

export const transactionsApi = {
  listForClient: (clientId, params) => api.get(`/clients/${clientId}/transactions${qs(params)}`),
  get: (id) => api.get(`/transactions/${id}`),
  // A fresh key per logical submission — retried requests (network blip, double
  // tap) reuse the browser's fetch retry with the same body but a new call here
  // would get a new key, so the key is generated by the caller once per form
  // submission and passed in (see TransactionFormModal) rather than per network call.
  create: (clientId, data, idempotencyKey) =>
    api.post(`/clients/${clientId}/transactions`, data, {
      headers: idempotencyKey ? { "Idempotency-Key": idempotencyKey } : {},
    }),
  update: (id, data) => api.put(`/transactions/${id}`, data),
  remove: (id) => api.del(`/transactions/${id}`),
};

export const CATEGORIES = ["Loan", "Salary", "Material", "Travel", "Food", "Rent", "Other"];
